name: Android Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # نصب Android SDK + cmdline-tools
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # نصب پلتفرم‌ها و بیلدتولز لازم
      - name: Install SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      # اجرای بیلد با Gradle (بدون نیاز به gradlew داخل ریپو)
      - name: Build with Gradle (no wrapper)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.6
          arguments: assembleDebug

      # خروجی APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hse-offline-debug-apk
          path: app/build/outputs/apk/debug/*.apk
